FitnessApp/Models/Trainer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FitnessApp.Models
{
    public class Trainer
    {
        [Required]
        public int Id { get; set; }

        [Required]
        [Display(Name ="Name")]
        [StringLength(50)]
        public string FullName { get; set; }

        [Required]
        [Display(Name = "Phone Number")]  
        [Phone]
        public string Phone { get; set; }

        [Display(Name = "E-mail")]
        [EmailAddress]
        [StringLength(30)]
        public string Email { get; set; }

        [StringLength(200)]
        public string Biography { get; set; }

        [StringLength(200)]
        public string Photo { get; set; }

        [Display(Name = "Photo")]
        public HttpPostedFileBase PhotoUpload { get; set; }
    }
}

FitnessApp/ViewModels/TrainerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FitnessApp.ViewModels
{
    public class TrainerViewModel
    {
        [Required]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Name")]
        [StringLength(50)]
        public string FullName { get; set; }

        [Required]
        [Display(Name = "Phone Number")]
        [Phone]
        public string Phone { get; set; }

        [Display(Name = "E-mail")]
        [EmailAddress]
        [StringLength(30)]
        public string Email { get; set; }

        [StringLength(200)]
        public string Biography { get; set; }

        [StringLength(200)]
        public string Photo { get; set; }

        [Display(Name = "Photo")]
        public HttpPostedFileBase PhotoUpload { get; set; }
    }
}

FitnessApp/Controllers/TrainersController.cs
using FitnessApp.Models;
using FitnessApp.Repository;
using FitnessApp.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace FitnessApp.Controllers
{
    public class TrainersController : Controller
    {
        private FitnessDb _context;

        public TrainersController()
        {
            _context = new FitnessDb();

        }


        // GET: Trainers
        //public ActionResult Index()
        //{
        //    return View();
        //}
        public ViewResult Index()
        {
            List<Trainer> trainers = _context.Trainers.ToList();
            List<TrainerViewModel> ltvm = new List<TrainerViewModel>();
            foreach (var item in trainers)
            {
                TrainerViewModel tvm = new TrainerViewModel();

                tvm.Biography = item.Biography;
                tvm.Email = item.Email;
                tvm.FullName = item.FullName;
                tvm.Id = item.Id;
                tvm.Phone = item.Phone;
                tvm.Photo = item.Photo;

                ltvm.Add(tvm);
            }

            return View(ltvm);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Trainer trainer = _context.Trainers.Single(x => x.Id == id);
            TrainerViewModel tvm = new TrainerViewModel();
            tvm.Biography = trainer.Biography;
            tvm.Email = trainer.Email;
            tvm.FullName = trainer.FullName;
            tvm.Id = trainer.Id;
            tvm.Phone = trainer.Phone;
            tvm.Photo = trainer.Photo;


            return View(tvm);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(TrainerViewModel trainer)
        {

            if (ModelState.IsValid)
            {
                if (trainer.PhotoUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(trainer.PhotoUpload.FileName);
                    string extension = Path.GetExtension(trainer.PhotoUpload.FileName);
                    fileName = trainer.FullName + "_" + DateTime.Now.ToString("dd-MM-yy hh-mm-ss") + extension;
                    trainer.Photo = "~/Images/Trainers/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/Images/Trainers/"), fileName);
                    trainer.PhotoUpload.SaveAs(fileName);



                }
                Trainer model = new Trainer();
                model.Biography = trainer.Biography;
                model.Email = trainer.Email;
                model.FullName = trainer.FullName;
                model.Id = trainer.Id;
                model.Phone = trainer.Phone;
                model.Photo = trainer.Photo;

                _context.Trainers.Add(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(trainer);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Trainer trainer = _context.Trainers.Find(id);

            TrainerViewModel tvm = new TrainerViewModel();
            tvm.Biography = trainer.Biography;
            tvm.Email = trainer.Email;
            tvm.FullName = trainer.FullName;
            tvm.Id = trainer.Id;
            tvm.Phone = trainer.Phone;
            tvm.Photo = trainer.Photo;

            return View("Edit", tvm);
        }

        [HttpPost]
        public ActionResult Edit(TrainerViewModel trainer)
        {
            if (!ModelState.IsValid)
                return View("Edit", trainer);

            var model = _context.Trainers.Find(trainer.Id);

            if (trainer.PhotoUpload != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(trainer.PhotoUpload.FileName);
                string extension = Path.GetExtension(trainer.PhotoUpload.FileName);
                fileName = trainer.FullName + "_" + DateTime.Now.ToString("dd-MM-yy hh-mm-ss") + extension;
                trainer.Photo = "~/Images/Trainers/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Images/Trainers/"), fileName);
                trainer.PhotoUpload.SaveAs(fileName);
            }
            else
                trainer.Photo = _context.Trainers.Single(x => x.Id == trainer.Id).Photo;

            model.Email = trainer.Email;
            model.Biography = trainer.Biography;
            model.FullName = trainer.FullName;
            model.Phone = trainer.Phone;
            model.Photo = trainer.Photo;

            _context.SaveChanges();

            //_context.Trainers.RemoveAt(index);
            //_context.Trainers.Insert(index, trainer);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var trainer = _context.Trainers.Find(id);

            _context.Trainers.Remove(trainer);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult SelectFromDropDown(TrainerViewModel trainer)
        {

            return View();
        }

        public ActionResult ListAllJson()
        {
            List<Trainer> trainers = _context.Trainers.ToList();
            List<TrainerViewModel> ltvm = new List<TrainerViewModel>();
            foreach (var item in trainers)
            {
                TrainerViewModel tvm = new TrainerViewModel();

                tvm.Biography = item.Biography;
                tvm.Email = item.Email;
                tvm.FullName = item.FullName;
                tvm.Id = item.Id;
                tvm.Phone = item.Phone;
                tvm.Photo = item.Photo;

                ltvm.Add(tvm);
            }

            return Json(ltvm, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ListAllDropDownList()
        {
            List<Trainer> trainers = _context.Trainers.ToList();
            List<TrainerViewModel> ltvm = new List<TrainerViewModel>();
            foreach (var item in trainers)
            {
                TrainerViewModel tvm = new TrainerViewModel();

                tvm.Biography = item.Biography;
                tvm.Email = item.Email;
                tvm.FullName = item.FullName;
                tvm.Id = item.Id;
                tvm.Phone = item.Phone;
                tvm.Photo = item.Photo;

                ltvm.Add(tvm);
            }

            return View(ltvm);
        }
    }
}

FitnessApp/Views/Trainers/Create.cshtml
@model FitnessApp.ViewModels.TrainerViewModel
@using FitnessApp.Repository
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h2>Create new trainer</h2>


@using (Html.BeginForm("Create", "Trainers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        <div class="form-group">
            <div class="align-content-lg-start my-lg-2">
                <div class="w-25">
                    @Html.LabelFor(m => m.FullName)
                    @Html.TextBoxFor(m => m.FullName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.FullName, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="align-content-lg-start my-lg-2">
                <div class="w-25">
                    @Html.LabelFor(m => m.Phone)
                    @Html.TextBoxFor(m => m.Phone, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Phone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="align-content-lg-start my-lg-2">
                <div class="w-25">
                    @Html.LabelFor(m => m.Email)
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="align-content-lg-start my-lg-2">
                <div class="w-25">
                    @Html.LabelFor(m => m.Biography)
                    @Html.TextAreaFor(m => m.Biography, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Biography, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="align-content-lg-start my-lg-2">
                <div class="w-25">
                    @Html.LabelFor(m => m.Photo)
                    <input type="file" name="PhotoUpload" />
                </div>
            </div>
        </div>
        <br />
        @*<input type="hidden" name="Id" value="@Model.Id" />*@
        <button type="submit" class="btn btn-primary">Save</button>
    </div>

}

FitnessApp/Views/Trainers/Details.cshtml
@model FitnessApp.ViewModels.TrainerViewModel
@using FitnessApp.Models
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string imgPath = Model.Photo == null ? "1" : Model.Photo;
}
<h2>@Model.FullName</h2>
<img src="@Url.Content(imgPath)" alt="No photo available" class="img-thumbnail" height="300" width="200">

<table class="table-sm">
    <tbody>        
        <tr>
            <td>Phone number:</td>
            <td>@Model.Phone</td>
        </tr>
        <tr>
            <td>Email:</td>
            <td>@Model.Email</td>
        </tr>
        <tr>
            <td>Biography:</td>
            <td>@Model.Biography</td>
        </tr>
    </tbody>
</table>
<br />
<p>@Html.ActionLink("Back to List", "Index")</p>

FitnessApp/Views/Trainers/Edit.cshtml
@model FitnessApp.ViewModels.TrainerViewModel
@using FitnessApp.Repository
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit trainer</h2>


@using (Html.BeginForm("Edit", "Trainers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div>
    <div class="form-group">
        <div class="align-content-lg-start my-lg-2">
            <div class="w-25">
                @Html.LabelFor(m => m.FullName)
                @Html.TextBoxFor(m => m.FullName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.FullName, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="align-content-lg-start my-lg-2">
            <div class="w-25">
                @Html.LabelFor(m => m.Phone)
                @Html.TextBoxFor(m => m.Phone, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Phone, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="align-content-lg-start my-lg-2">
            <div class="w-25">
                @Html.LabelFor(m => m.Email)
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="align-content-lg-start my-lg-2">
            <div class="w-25">
                @Html.LabelFor(m => m.Biography)
                @Html.TextAreaFor(m => m.Biography, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Biography, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="align-content-lg-start my-lg-2">
            <div class="w-25">
                @Html.LabelFor(m => m.Photo)
                <input type="file" name="PhotoUpload" />
            </div>
        </div>
    </div>
    <br />
    @Html.HiddenFor(model => model.Id)
    <button type="submit" class="btn btn-primary">Save</button>
</div>

}

FitnessApp/Views/Trainers/Index.cshtml
@using FitnessApp.ViewModels
@model List<TrainerViewModel>
@{
    ViewBag.Title = "ListAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Trainers</h2>
<a class="btn btn-primary" href="@Url.Action("Create", "Trainers")" role="button">Create new</a>
<br>
<br>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Phone Number</th>
            <th scope="col">E-mail</th>
            <th scope="col">Biography</th>
            <th scope="col">Photo</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var trainer in Model)
        {
            <tr>
                <td>@trainer.Id</td>
                <td>@Html.ActionLink(trainer.FullName, "Details", new { id = trainer.Id })</td>
                <td>@trainer.Phone</td>
                <td>@trainer.Email</td>
                <td>@trainer.Biography</td>
                <td>@trainer.Photo</td>
                <td>@Html.ActionLink("Edit", "Edit", new { id = trainer.Id }, new { @class = "btn btn-primary" })</td>
                <td>
                    @using (Html.BeginForm("Delete", "Trainers", new { id = trainer.Id }))
                    {
                        <button class="btn btn-primary" type="submit"
                                onclick="return confirm('Are you sure you want to delete @trainer.FullName')">
                            Delete
                        </button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

FitnessApp/Views/Trainers/ListAllDropDownList.cshtml
@model List<FitnessApp.ViewModels.TrainerViewModel>


@{
    ViewBag.Title = "ListAllDropDownList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ListAllDropDownList</h2>

<form action="/" method="post"></form>
<select id="z">
    <option selected disabled="disabled">Избери држава</option>
    @foreach (var item in Model)
    {
        <option>
            @item.FullName
        </option>
    }

</select>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script>

    $(document).ready(function () {


        var selectDropDown = $("#z");

        selectDropDown.change(function () {
        selectDropDown.empty();
        selectDropDown.append('<option value="">-- Избери држава --</option>');
        selectDropDown.prop('selectedIndex', 0);

        $.ajax({
            url: "http://localhost:49998/Trainers/ListAllJson/",
            dataType: 'json',
            success: function (res) {


                for (var i = 0; i < res.length; i++) {
                    console.log(res[i].FullName, res[i].Id);
                    selectDropDown.append(`<option value="${res[i].Id}">${res[i].FullName}</option>`);



                }
            }
        });

        //$.ajax({

        //    .....
        //    ....

        //});

        //$.ajax({
        //    method: "GET",
        //    url: "http://localhost:49998/Trainers/ListAllJson/",
        //    dataType: "json",
        //    success: function (data) {
        //        console.log("aaaaaaaaaaaaaaa");
        //    },
        //    error: function (e) {
        //        console.log(e);
        //    }
        //});




        //for (var i = 0; i < length; i++) {

        //}
        //selectDropDown.append('<option value="mercedes">Mercedes</option>');

        });

        console.log("ready!");
    });

</script>

FitnessApp/Views/Trainers/SelectFromDropDown.cshtml
@{
    ViewBag.Title = "SelectFromDropDown";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SelectFromDropDown</h2>
<form action="/SelectFromDropDown" method="post">
    @*<select name="cars" id="zdsd">
        <option value="xxx">Избери држава</option>
    <option value="saab">Saab</option>

    </select>
    *@
    <input type="text" name="name" value="" />

    <input type="submit" name="name" value="потврди" />

    <br>
    <label for="sel1">Select list:</label>
    <br>
    @*<select id="z">
            <option>Избери држава</option>
            <option>2</option>

        </select>*@

    <select id="z">
        <option selected disabled="disabled">--Избери држава--</option>
        @*<option value="">-- Избери држава --</option>*@
    </select>



</form>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script>

    $(document).ready(function () {
     
    
        var selectDropDown = $("#z");

        selectDropDown.change(function () {
        selectDropDown.empty();
        selectDropDown.append('<option value="">-- Избери држава --</option>');
        selectDropDown.prop('selectedIndex', 0);
      
        $.ajax({
            url: "http://localhost:49998/Trainers/ListAllJson/",
            dataType: 'json',
            success: function (res) {

                
                for (var i = 0; i < res.length; i++) {
                    console.log(res[i].FullName, res[i].Id);
                    selectDropDown.append(`<option value="${res[i].Id}">${res[i].FullName}</option>`);

                    
                    
                }
            }
        });

        //$.ajax({

        //    .....
        //    ....

        //});

        //$.ajax({
        //    method: "GET",
        //    url: "http://localhost:49998/Trainers/ListAllJson/",
        //    dataType: "json",
        //    success: function (data) {
        //        console.log("aaaaaaaaaaaaaaa");
        //    },
        //    error: function (e) {
        //        console.log(e);
        //    }
        //});




        //for (var i = 0; i < length; i++) {

        //}
        //selectDropDown.append('<option value="mercedes">Mercedes</option>');

        });

        console.log("ready!");
    });

</script>