FitnessApp/ViewModels/TrainingTypeViewModel.cs
using FitnessApp.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FitnessApp.ViewModels
{
    public class TrainingTypeViewModel
    {
        [Required]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Training")]
        public string Name { get; set; }

        [StringLength(200)]
        public string Description { get; set; }

        [StringLength(200)]
        public string Photo { get; set; }

        [Display(Name = "Photo")]
        public HttpPostedFileBase PhotoUpload { get; set; }

        [Required]
        public int TrainerId { get; set; }
    }
}

FitnessApp/Controllers/TrainingTypesController.cs
using FitnessApp.Models;
using FitnessApp.Repository;
using FitnessApp.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FitnessApp.Controllers
{
    public class TrainingTypesController : Controller
    {

        private FitnessDb _context;

        public TrainingTypesController()
        {
            _context = new FitnessDb();

        }

        public ViewResult Index()
        {

            List<TrainingType> trainingTypes = new List<TrainingType>();
            
            trainingTypes = _context.TrainingTypes.ToList();
            List<TrainingTypeIndexViewModel> lttvm = new List<TrainingTypeIndexViewModel>();
            foreach (var item in trainingTypes)
            {

                var tr = _context.Trainers.Find(item.TrainerId);
                TrainingTypeIndexViewModel ttvm = new TrainingTypeIndexViewModel();

                ttvm.Description = item.Description;
                var hh = new Trainer();
                ttvm.Trainer = hh;

                ttvm.Trainer.FullName = tr.FullName;
                ttvm.Trainer.Email = tr.Email;
                ttvm.Trainer.Phone = tr.Phone;
                ttvm.Name = item.Name;
                ttvm.Id = item.Id;
                ttvm.Photo = item.Photo;

                lttvm.Add(ttvm);
            }

            return View(lttvm);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            TrainingType training = new TrainingType();
            training = _context.TrainingTypes.Find(id);
            Trainer trainer = new Trainer();
            trainer = _context.Trainers.Find(training.TrainerId);
            training.Trainer = new Trainer();
            TrainingTypeDetailsViewModel tt = new TrainingTypeDetailsViewModel();
            tt.Trainer = new Trainer();
            tt.Trainer.FullName = trainer.FullName;
            tt.Name = training.Name;
            tt.Photo = training.Photo;
            tt.Id = training.Id;
            return View(tt);
        }

        [HttpGet]
        public ActionResult Create()
        {
            List<Trainer> trainers = _context.Trainers.ToList();
            var ViewModel = new TrainingTypeTrainerViewModel()
            {
                Trainers = trainers
            };
            return View(ViewModel);
        }

        [HttpPost]
        public ActionResult Create(TrainingTypeTrainerViewModel viewModel)
        {         
            if (ModelState.IsValid)
            {
                if (viewModel.TrainingType.PhotoUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(viewModel.TrainingType.PhotoUpload.FileName);
                    string extension = Path.GetExtension(viewModel.TrainingType.PhotoUpload.FileName);
                    fileName = viewModel.TrainingType.Name + "_" + DateTime.Now.ToString("dd-MM-yy hh-mm-ss") + extension;
                    viewModel.TrainingType.Photo = "~/Images/TrainingTypes/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/Images/TrainingTypes/"), fileName);
                    viewModel.TrainingType.PhotoUpload.SaveAs(fileName);
                }              
            }
            
            int t = viewModel.TrainingType.TrainerId;
            var yy = _context.Trainers.Find(t);

            var model = new TrainingType()
            {
                Description = viewModel.TrainingType.Description,
                Name = viewModel.TrainingType.Name,

                Photo = viewModel.TrainingType.Photo,
                Trainer = yy
            };

            _context.TrainingTypes.Add(model);
            _context.SaveChanges();
            return RedirectToAction("Index");
            
        }

        [HttpPost]
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var trainingTypes = _context.TrainingTypes.Find(id);

            _context.TrainingTypes.Remove(trainingTypes);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            TrainingType modelTrainingType = new TrainingType();
            modelTrainingType = _context.TrainingTypes.Find(id);
            var modelTrainer = _context.Trainers.Find(modelTrainingType.TrainerId);
            modelTrainingType.Trainer = new Trainer();
            modelTrainingType.Trainer = modelTrainer;

            return View(modelTrainingType);
        }



        [HttpPost]
        public ActionResult Edit(TrainingTypeViewModel trainingType)
        {
            if (!ModelState.IsValid)
                return View("Edit", trainingType);

            var modelTrainingType = _context.TrainingTypes.Find(trainingType.Id);
            var model2 = _context.Trainers.Find(modelTrainingType.TrainerId);
            if (trainingType.PhotoUpload != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(trainingType.PhotoUpload.FileName);
                string extension = Path.GetExtension(trainingType.PhotoUpload.FileName);
                fileName = trainingType.Name + "_" + DateTime.Now.ToString("dd-MM-yy hh-mm-ss") + extension;
                trainingType.Photo = "~/Images/Trainers/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Images/Trainers/"), fileName);
                trainingType.PhotoUpload.SaveAs(fileName);
            }
            else
                trainingType.Photo = _context.Trainers.Single(x => x.Id == trainingType.Id).Photo;

            modelTrainingType.Id = trainingType.Id;
            modelTrainingType.Description = trainingType.Description;
            modelTrainingType.Name = trainingType.Name;
            modelTrainingType.Photo = trainingType.Photo;

            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

FitnessApp/Views/TrainingTypes/Create.cshtml
@model FitnessApp.ViewModels.TrainingTypeTrainerViewModel
@using FitnessApp.Repository
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create new training</h2>



@using (Html.BeginForm("Create", "TrainingTypes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        <div class="form-group">
            <div class="align-content-lg-start my-lg-2">
                <div class="w-25">
                    @Html.LabelFor(m => m.TrainingType.Name)
                    @Html.TextBoxFor(m => m.TrainingType.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.TrainingType.Name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="align-content-lg-start my-lg-2">
                <div class="w-25">
                    @Html.LabelFor(m => m.TrainingType.Description)
                    @Html.TextBoxFor(m => m.TrainingType.Description, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.TrainingType.Description, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="align-content-lg-start my-lg-2">
                <div class="w-25">
                    @Html.LabelFor(m => m.TrainingType.TrainerId)
                    @Html.DropDownListFor(m => m.TrainingType.TrainerId, new SelectList(Model.Trainers, "Id", "FullName" ), "Select trainer", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.TrainingType.TrainerId, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>        
        <div class="form-group">
            <div class="align-content-lg-start my-lg-2">
                <div class="w-25">
                    @Html.LabelFor(m => m.TrainingType.Photo)
                    @Html.TextBoxFor(m=>m.TrainingType.PhotoUpload, "", new {type="file" })
                    @*<input type="file" name="TrainingType.PhotoUpload" />*@
                </div>
            </div>


        </div>
        <br />
        @*<input type="hidden" name="Id" value="@(Model.TrainingType.Id)" />*@
        <button type="submit" class="btn btn-primary">Save</button>
    </div>

}

FitnessApp/Views/TrainingTypes/Details.cshtml
@model FitnessApp.ViewModels.TrainingTypeDetailsViewModel
@using FitnessApp.Models
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string imgPath = Model.Photo == null ? "1" : Model.Photo;
}
<h2>@Model.Name</h2>
<img src="@Url.Content(imgPath)" alt="No photo available" class="img-thumbnail" height="300" width="200">

<table class="table-sm">
    <tbody>
        <tr>
            <td>Trainer type:</td>
            <td>@Model.Name</td>
        </tr>
        <tr>
            <td>Trainer Full name:</td>
            <td>@Model.Trainer.FullName</td>
        </tr>
    </tbody>
</table>
<br />
<p>@Html.ActionLink("Back to List", "Index")</p>

FitnessApp/Views/TrainingTypes/Edit.cshtml
@model FitnessApp.Models.TrainingType
@using FitnessApp.Repository
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Training type</h2>


@using (Html.BeginForm("Edit", "TrainingTypes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        <div class="form-group">
            <div class="align-content-lg-start my-lg-2">
                <div class="w-25">
                    @Html.LabelFor(m => m.Name)
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="align-content-lg-start my-lg-2">
                <div class="w-25">
                    @Html.LabelFor(m => m.Description)
                    @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
       
        <div class="form-group">
            <div class="align-content-lg-start my-lg-2">
                <div class="w-25">
                    @Html.LabelFor(m => m.Photo)
                    <input type="file" name="PhotoUpload" />
                </div>
            </div>
        </div>
        <br />
        @Html.HiddenFor(model => model.Id)
        <button type="submit" class="btn btn-primary">Save</button>
    </div>

}

FitnessApp/Views/TrainingTypes/Index.cshtml
@using FitnessApp.ViewModels
@model List<TrainingTypeIndexViewModel>
@{
    ViewBag.Title = "ListAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Trainings</h2>
<a class="btn btn-primary" href="@Url.Action("Create", "TrainingTypes")" role="button">Create new</a>
<br>
<br>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Trainer</th>
            <th scope="col">Photo</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var training in Model)
        {
            <tr>
                <td>@training.Id</td>
                <td>@Html.ActionLink(training.Name, "Details", new { id = training.Id })</td>
                <td>@training.Description</td>
                <td>@training.Trainer.FullName</td>
                <td>@training.Photo</td>
                <td>@Html.ActionLink("Edit", "Edit", new { id = training.Id }, new { @class = "btn btn-primary" })</td>
                <td>
                    @using (Html.BeginForm("Delete", "TrainingTypes", new { id = training.Id }))
                    {
                        <button class="btn btn-primary" type="submit" onclick="return confirm('Are you sure you want to delete @training.Name')">
                            Delete
                        </button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

FitnessApp/Views/TrainingTypes/ListAll.cshtml
@using FitnessApp.ViewModels
@model List<TrainingTypeViewModel>
@{
    ViewBag.Title = "ListAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Trainings</h2>
<a class="btn btn-primary" href="@Url.Action("Create", "TrainingTypes")" role="button">Create new</a>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Trainer</th>
            <th scope="col">Photo</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var training in Model)
        {
            <tr>
                <td>@training.Id</td>
                <td>@Html.ActionLink(training.Name, "Details", new { id = training.Id })</td>
                <td>@training.Description</td>
                <td>@training.Trainer.FullName</td>
                <td>@training.Photo</td>
                <td>@Html.ActionLink("Edit", "Edit", new { id = training.Id }, new { @class = "btn btn-primary" })</td>
                <td>
                    @using (Html.BeginForm("Delete", "TrainingTypes", new { id = training.Id }))
                    {
                        <button class="btn btn-primary" type="submit" onclick="return confirm('Are you sure you want to delete @training.Name')">
                            Delete
                        </button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>